### ISSUE TITLE
Apply clearance to funnel algorithm when the path is not obstructed

### ISSUE THREAD

**Issue by shanek21** [chauncy-crib/tagprobot#307] opened 2017-12-17 01:41 UTC
It looks like clearance is only applied on the funneled path once the path is obstructed by an obstacle. The picture below shows an example.

![300_bug.png](https://images.zenhubusercontent.com/5963b3c261b4ca3b0a73e119/231baa78-e4af-40aa-98ad-b5bad39324b8)

**Comment by billmwong** [comment] 2017-12-18 20:06
Duplicate of #319, this one has a cool screenshot but I already made a branch name with 319

**Closed by billmwong** 2017-12-18 20:06 UTC
Labels: bug
